/* This file generated by bsmuiicons */
module Search = MUIIcons_Search;
module SearchOutlined = MUIIcons_SearchOutlined;
module SearchRounded = MUIIcons_SearchRounded;
module SearchTwoTone = MUIIcons_SearchTwoTone;
module SearchSharp = MUIIcons_SearchSharp;
