/* This file generated by bsmuiicons */
module Search = MuiIcons_Search;
module SearchOutlined = MuiIcons_SearchOutlined;
module SearchRounded = MuiIcons_SearchRounded;
module SearchTwoTone = MuiIcons_SearchTwoTone;
module SearchSharp = MuiIcons_SearchSharp;
