const { src, series } = require('gulp');
const del = require('del');
const tap = require('gulp-tap');
const fse = require('fs-extra');

let memory = {};
memory.nameList = 
`/* This file generated by gulp */
module.exports = [`;

function deleteIconNames(cb) {
  return del('./iconNames.js');
}

function loadMuiIcons() {
  return src('./node_modules/@material-ui/icons/*.js')
    .pipe(tap(function(file) {
      if (file.stem !== 'index' && !file.stem.match(/(Outlined|Rounded|TwoTone|Sharp)$/)) {
        memory.nameList += "'" + file.stem + "',";
      }
    }));
}

async function buildIconNames() {
  try {
    let contents = memory.nameList + '];';
    await fse.outputFile('./iconNames.js', contents);
  } catch (err) {
    console.error(err);
  }
}

exports.buildIconNames = series(
  deleteIconNames,
  loadMuiIcons,
  buildIconNames
);