const { src, series } = require('gulp');
const del = require('del');
const tap = require('gulp-tap');
const fse = require('fs-extra');

let memory = {};
memory.nameList = 
`/* This file generated by gulp */
module.exports = [`;

function deleteMaterialIconList(cb) {
  return del('./materialIconList.js');
}

function loadMaterialIconList() {
  return src('./node_modules/@material-ui/icons/*.js')
    .pipe(tap(function(file) {
      if (file.stem !== 'index' && !file.stem.match(/(Outlined|Rounded|TwoTone|Sharp)$/)) {
        memory.nameList += "'" + file.stem + "',";
      }
    }));
}

async function buildMaterialIconList() {
  try {
    let contents = memory.nameList + '];';
    await fse.outputFile('./materialIconList.js', contents);
  } catch (err) {
    console.error(err);
  }
}

exports.buildMaterialIconList = series(
  deleteMaterialIconList,
  loadMaterialIconList,
  buildMaterialIconList
);